name: Node.js CI

# Define when the workflow should run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # Define matrix for OS and Node.js versions
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # You can switch windows-latest with macos-latest if preferred
        node-version: [18, 20, 22]

    steps:
      # Checkout the latest code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Node.js based on matrix version
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          # Add custom OS-specific commands if necessary
          npm install

      # Run tests
      - name: Run tests
        run: |
          npm test
